classDiagram
    DefaultUser ..|> User : implements
    UserDecorator ..|> User : implements
    Admin --|> UserDecorator : extends
    Staff --|> UserDecorator : extends
    Student --|> UserDecorator : extends
    UserDecorator *-- User : composition
    class User{
        &lt;&lt;interface&gt;&gt;
        +getUserName()
        +logOut()
    }
    class DefaultUser{
        +DefaultUser()
        +getUserName()
        +logOut()
    }
    class UserDecorator{
        User wrappedComponent
        UserDecorator(User)
        +getUserName()
        +logOut()
    }
    class Admin{
        +Admin(User)
        +getUserName()
        +logOut()
        +checkRequests()
        +approveRequest()
    }
    class Instructor{
        +Instructor(User)
        +getUserName()
        +logOut()
        +checkRequests()
        +approveRequest()
    }
    class Staff{
        +Staff(User)
        +getUserName()
        +logOut()
        +checkRequests()
        +approveRequests()
    }
    class Student{
        +Student(User)
        +getUserName()
        +logOut()
        +requestEnroll()
        +dropClass()
        +checkSchedule()
    }
