classDiagram

    StudentView ..|> ViewState : implements
    InstructorView ..|> ViewState : implements
    AdminView ..|> ViewState : implements
    User --> ViewContext
    ViewContext *.. ViewState : composition


    class User

    class ViewContext {
        -ViewState state

        +changeView() : "state.doStuff()"
    }

    class ViewState {
        <<interface>>
        +doStuff()
    }
    class StudentView {
        -ViewContext context

        +doStuff()
    }
    class InstructorView {
        -ViewContext context

        +doStuff()
    }
    class AdminView {
        -ViewContext context

        +doStuff()
    }